### PR TITLE
chore: migrate to docusaurus v3

### PR DESCRIPTION
**Pull request by EscapedGibbon**

### CODE REVIEW

**Comment by stropitek** [comment]
Searching does not always give the expected results.

It seems like words which are in a page / section with a demo are not indexed.

@EscapedGibbon can you confirm this?

**Comment by EscapedGibbon** [comment]
> Searching does not always give the expected results.
> 
> It seems like words which are in a page / section with a demo are not indexed.
> 
> @EscapedGibbon can you confirm this?

No, I don't think there is a correlation between pages with demos and index problems. For instance, the word "comparison" is in `Comparison.md` and `Getting started.md` none of which have demos.  At the same time, it can find the word `grayscale` everywhere (regardless of whether the page has a demo or not) but not on the `Working with ROIs.md` where there is no demo and `Morphological Gradient.md` where a demo exists.

**Comment by targos** [comment]
"Working with ROIs" seems to not be indexed at all. I can't even find it using the title.

**Comment by stropitek** [comment]
CleanShot 2024-02-09 at 11 25 48

Also if you click on "find all results" (barely visible), you are redirected to a 404 page

**Comment by EscapedGibbon** [comment]
Small update. I think I solved the indexing issue. The pages get indexed based on the HTML headers(h1,h2 etc.) So, if the page doesn't have any headers ( which was the case with "Working with ROIs") then it was basically considered empty by search engine. I added h1 titles to each page. It should solve the problem without changing pages in any way. However, now when there are too many results, the "See all X results" thing doesn't work properly and goes to an invalid link.

**Comment by stropitek** [comment]
> However, now when there are too many results, the "See all X results" thing still doesn't work properly and goes to an invalid link.

Yes this is a completely independent problem

I find the ranking when searching multiple words inadequate. There is only one page containing the word "contiguous" but when I search "contiguous black" (the said page has both), it is not the first result.

CleanShot 2024-02-27 at 10 18 29

CleanShot 2024-02-27 at 10 18 55

**Comment by EscapedGibbon** [comment]
I will take a look at it one more time tomorrow, but I don't know why it is ranking words this way. In previous versions, it just stacked the first word results at first and second word results after, so I thought that the new version just put the last word results on top. But this is not the case.

**Comment by stropitek** [comment]
I was able to debug what happens in `@orama/searchbox` by enable source maps everywhere:

CleanShot 2024-04-28 at 13 01 36@2x


But I did not find anything suspicious. The results are shown in order from highest to lowest score.

Documentation website of Node.js uses orama and there are kind of similar issues if you try to find a very specific piece of text with multiple keywords. It's just how it works.

Orama does a good job when searched with simple keywords. If I compare with the current docs site and search things like filter names (median, grayscale) I find the results to be good (better than the current search box)

What needs to be improved is that it does not link to the section in which it found the result. After this is merged, please create an issue for that.

This can be merged after the orama dependencies have been updated.

**Comment by stropitek** [comment]
Please keep the scope of this PR to updating docusaurus related dependencies.

**Comment by EscapedGibbon** [comment]
Currently PR cannot be merged because the orama plugin has issues with docusaurus plugin which blocks the merge. Waiting for updates from docusaurus for orama to work.
Also this PR must resolve #110.

**Comment by stropitek** [comment]
Is there a reason this is still in draft?

**Review by stropitek — APPROVED** [review]

**Pull request merged**
