### PR TITLE
docs: change the doc title

### PR DESCRIPTION
**Pull request by EscapedGibbon**
close: https://github.com/image-js/image-js-docs/issues/76

### CODE REVIEW

**Comment by stropitek** [comment]
ImageJS vs Image-JS are used across the docs

We should pick one (I forgot our original decision)

**Comment by EscapedGibbon** [comment]
> ImageJS vs Image-JS are used across the docs
> 
> We should pick one (I forgot our original decision)

In documentation, we decided to go with ImageJS but I can't remember why exactly. Personally, ImageJS looks nicer than Image-JS imho.

**Comment by stropitek** [comment]
You can make it consistent in this PR

**Comment by stropitek** [comment]
If you search for `image-js` in the search there is still a result

**Comment by EscapedGibbon** [comment]
> If you search for `image-js` in the search there is still a result

Fixed. The rest, I believe, are mentions in configs.

**Review by stropitek — APPROVED** [review]

**Pull request merged**
