### PR TITLE
86 add roi analysis tutorial

### PR DESCRIPTION
**Pull request by EscapedGibbon**
close: https://github.com/image-js/image-js-docs/issues/86

### CODE REVIEW

**Comment by stropitek** [comment]
Should be the first thing to say in the tutorial

Also no need to make it a warning, it can be just a "note"

CleanShot 2024-02-13 at 16 58 53

**Comment by stropitek** [comment]
I don't think anyone wants to read a long list of numbers in a table with many digits

You can show the distribution in a graph or add the value in the image next to the region of interest (but cut the many digits)

**Comment by stropitek** [comment]
CleanShot 2024-02-16 at 10 13 43

It would make more sense to draw a horizontal line here to show where the cutoff is. You can put "nuts" and "washers" in a legend with the right color association.

Also the cutoff you chose is overfitting the data and probably does not generalize well on new images of nuts and washers. No need to start expanding on classifiers, but you should mention it.

**Comment by stropitek** [comment]
I really think the table of numbers can go away.

**Comment by stropitek** [comment]
@targos can you review the page on metadata?

https://86-add-roi-analysis-tutorial.image-js-docs.pages.dev/docs/Tutorials/Extracting%20metadata

**Comment by targos** [comment]
The contents look fine and we can merge it, but I would not have agreed to doing a tutorial on metadata at this point. This is one of the less stable and thought of APIs in ImageJS.

About "Getting extra data", maybe mention somewhere that it is XML? It's weird to use a custom-made parser to handle it.

**Comment by EscapedGibbon** [comment]
> The contents look fine and we can merge it, but I would not have agreed to doing a tutorial on metadata at this point. This is one of the less stable and thought of APIs in ImageJS.
> 
> About "Getting extra data", maybe mention somewhere that it is XML? It's weird to use a custom-made parser to handle it.

Added the mention.

**Comment by stropitek** [comment]
When referring to classifiers, maybe use a more specific reference. "Machine learning" is a very broad term.

https://en.wikipedia.org/wiki/Statistical_classification

**Review by stropitek — APPROVED** [review]
LGTM, just update the link

**Comment by EscapedGibbon** [comment]
> LGTM, just update the link

Done

**Pull request merged**
